# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


variables:
  vmImage: ubuntu-latest
  pythonVersion: '3.9'

stages:
- stage: Compilation
  displayName: Compilation stage
  jobs:
  - job: CompilationJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - script: python -m py_compile app.py
      displayName: 'Test compilation'
